services:
  api:
    container_name: products_api
    build: . 
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env 
    depends_on:
      - mongo 

  mongo:
    container_name: products_mongo
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db 

# Define the named volume for data persistence
volumes:
  mongodb_data: